return {
    { "nvim-neo-tree/neo-tree.nvim", enabled = false },
    { "folke/twilight.nvim", enabled = false },
    { "ggandor/leap.nvim", enabled = false },
    { "ggandor/flit.nvim", enabled = false },
    -- { "stevearc/dressing.nvim", enabled = false },
    { "sekke276/dark_flat.nvim", enabled = false },
    { "ray-x/lsp_signature.nvim", enabled = false },
    { "goolord/alpha-nvim", enabled = false },
    { "yamatsum/nvim-cursorline", enabled = false },
    { "RRethy/vim-illuminate", enabled = false },
    -- { "olimorris/onedarkpro.nvim", enabled = false },
    -- { "anuvyklack/pretty-fold.nvim", eanabled = false },
    -- { "kevinhwang91/nvim-ufo", enabled = false },
    { "nvimdev/lspsaga.nvim", enabled = false },
}
